### ISSUE TITLE
xml file not saved as utf8

### ISSUE THREAD

**Issue by fxpar** [mist13/abc2xmlGUI#2]
Hi
It seems that the xml output is not in utf8 encoding but in ANSI.
(the xml file contains the ut-8 encoding instruction, but the content of the file is not saved in utf8 encoding).

Platform windows 
release Guy1.1

T: Encyclop**é**die des Gammes

The accent on the é, will raise an error when importing in musescore for example.

**Comment by fxpar** [comment]
Maybe changing line 313
from 
`filename.write(content)`
To 
`filename.write(foo.encode(content))`
Will do the trick... Other forum says the file should be opened with utf8 as parameter but I didn't find the "open" instruction in the code, sorry.

**Comment by mist13** [comment]
Hi François,
Thank you for pointing this out to me. It will take a little while before I can have a proper look.
Michael

**Comment by mist13** [comment]
Fixed in version 1.2
